In [1]:
from sklearn import datasets
import numpy as np

In [2]:
iris = datasets.load_iris(as_frame=True)

### Explorando el conjunto de datos

In [ ]:
datasets.load_iris?

In [3]:
## caracteristicas existentes en el dataset
iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

<img src="https://dr282zn36sxxg.cloudfront.net/datastreams/f-d%3A622deeb06ecd07a64dcb2a3a29dc4ccc892b8d1d374b6fe382c8cca4%2BIMAGE_TINY%2BIMAGE_TINY.1">

In [4]:
# valores de la variable objetivo
iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
# variable objetivo
iris["target"].head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [6]:
#conjunto de datos
iris["data"].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
# DataFrame devuelto por la libreria
iris["frame"].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

### Seleccionando conjunto de datos de entrenamiento y test

In [8]:
X = iris["data"]
y = iris["target"]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=13)

In [ ]:
train_test_split?

Dado que los modelos de scikit-learn están optimizados para funcionar con variables normalizadas o estandarizadas, resulta conveniente estandarizar nuestro conjunto de datos, para ello utilizamos un modulo de preprocesamiento existente en **Scikit Learn**

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [ ]:
X_train_std[:10]

array([[ 1.6414058 ,  1.35045695,  1.37610194,  1.77370775],
       [-0.81902913,  0.86732925, -1.23551785, -1.26855377],
       [-0.9361927 , -1.78987309, -0.21357967, -0.21037585],
       [-1.63917411,  0.38420155, -1.34906654, -1.26855377],
       [ 0.82126082, -0.58205385,  0.52448679,  0.45098535],
       [-0.11604772,  1.83358464, -1.12196917, -1.13628153],
       [-0.11604772, -0.09892615,  0.29738942,  0.05416863],
       [ 0.11827941,  0.38420155,  0.63803548,  0.84780207],
       [ 1.17275153,  0.38420155,  1.26255325,  1.50916327],
       [-1.05335627,  0.1426377 , -1.23551785, -1.400826  ]])

In [ ]:
X_test_std[:10]

array([[-1.16047725e-01, -5.82053846e-01,  4.67712448e-01,
         1.86440871e-01],
       [-2.33211293e-01, -3.40489997e-01, -4.32566426e-02,
         1.86440871e-01],
       [-8.19029134e-01,  1.59202079e+00, -1.23551785e+00,
        -1.00400929e+00],
       [ 1.11584351e-03, -8.23617694e-01,  8.08358508e-01,
         9.80074309e-01],
       [ 1.17275153e+00, -9.89261477e-02,  1.03545588e+00,
         1.24461879e+00],
       [-3.50374861e-01,  2.79984004e+00, -1.29229220e+00,
        -1.26855377e+00],
       [ 2.22722364e+00, -9.89261477e-02,  1.37610194e+00,
         1.50916327e+00],
       [ 5.86933684e-01, -8.23617694e-01,  6.94809821e-01,
         8.47802069e-01],
       [-8.19029134e-01,  1.83358464e+00, -1.17874351e+00,
        -1.26855377e+00],
       [-3.50374861e-01, -1.06518154e+00,  4.10938104e-01,
         5.41686315e-02]])

Como es de apreciar tenemos la misma información suministrada por el dataset, pero en este caso se encuentra completamente estandarizada

## Construimos nuestro perceptron

In [11]:
from sklearn.linear_model import Perceptron

In [ ]:
Perceptron?

In [12]:
ppn = Perceptron(max_iter=50, eta0=0.1, random_state=13)
ppn.fit(X_train_std,y_train)

Perceptron(eta0=0.1, max_iter=50, random_state=13)

http://www.benfrederickson.com/numerical-optimization/

## Realizamos las predicciones con base en nuestros datos de prueba

In [13]:
y_pred = ppn.predict(X_test_std)

In [ ]:
y_pred

array([1, 1, 0, 2, 2, 0, 2, 1, 0, 1, 2, 1, 1, 0, 2, 0, 2, 2, 1, 0, 1, 0,
       0, 2, 1, 2, 0, 2, 1, 2, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       2])

In [14]:
print("""
    El número de aciertos: {}
    El número de errores: {}
    El porcentaje de aciertos: {}
    El porcentaje de errores: {}
""".format(
    (y_pred == y_test).sum(),
    (y_pred != y_test).sum(),
    ((y_pred == y_test).sum())/len(y_pred),
    ((y_pred != y_test).sum())/len(y_pred)
))


    El número de aciertos: 41
    El número de errores: 4
    El porcentaje de aciertos: 0.9111111111111111
    El porcentaje de errores: 0.08888888888888889

